### PR TITLE
FIX: Twitter Regex

### PR DESCRIPTION
**Pull request by takky94**
A query parameter has been added to the link when `Copy link to tweet` is pressed

image

demo:
156863728-174252cd-aa18-4b40-a63a-0acfea581b92

### CODE REVIEW

**Review by neSpecc — COMMENTED** [review]
Could you add a test for this case?

**Comment by takky94** [comment]
It's done, thank you :)

**Comment by neSpecc** [comment]
Could you please increment a patch version and we will be ready to merge

**Review by neSpecc — APPROVED** [review]

**Review by ilyamore88 — APPROVED** [review]

**Comment by neSpecc** [comment]
Thanks @takky94 @ilyamore88

**Pull request merged**
