### PR TITLE
fix: twitter (support both x.com and twitter.com) urls

### PR DESCRIPTION
**Pull request by hortopan**
Twitter.com now uses x.com in main urls.

### CODE REVIEW

**Review by neSpecc — COMMENTED** [review]
Thank you. Please add a corresponded testcase(s)

And increment a patch version

**Review by neSpecc — APPROVED** [review]

**Comment by neSpecc** [comment]
Tests are failed, could you check?

**Comment by hortopan** [comment]
> Tests are failed, could you check?

Sorry about that. I was sloppy with the regex in the initial commit.

**Review by neSpecc — CHANGES_REQUESTED** [review]
`yarn.lock` should not be changed here

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
