### PR TITLE
add github service

### LINKED ISSUE #82: Adding gist github service
Hi, i am trying to add gist github service but it is not working. This is what i tried

```
'github': {
              regex: /https?:\/\/gist.github.com\/([^\/\?\&]*)\/([^\/\?\&]*)/,
              embedUrl: 'https://gist.github.com/<%= remote_id %>',
              html: "<iframe height='300' scrolling='no' frameborder='no' allowtransparency='true' allowfullscreen='true' style='width: 100%;'></iframe>",
              height: 300,
              id: (groups) => groups.join('/')
          }
```

What am i doing wrong?

### PR DESCRIPTION
**Pull request by jefcolbi**
This is the code required to add github gist service.

Resolves #82

### CODE REVIEW

**Review by neSpecc — CHANGES_REQUESTED** [review]
Please, add a test case for that update

**Comment by jefcolbi** [comment]
@neSpecc hi. Please i am not a Javascript developer. i managed to have a friend help me for that. So for the test case i don't know what to do. You can be kind by writing a test case please.
Thanks

**Comment by userharis** [comment]
I have added tests, and applied some needed fixes. See this [pen](https://codepen.io/haris_dev/pen/dydPRgm?editors=1010).
please see https://github.com/jefcolbi/embed/pull/1

**Comment by jefcolbi** [comment]
@userharis i merged thanks.

**Comment by jefcolbi** [comment]
Hi. Can this be merged? changes have been applied

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
